"""removed vertical from company table

Revision ID: 03aa45522316
Revises: 76a41f56456f
Create Date: 2024-11-27 10:45:05.585580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03aa45522316'
down_revision: Union[str, None] = '76a41f56456f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_companies_vertical', table_name='companies')
    op.drop_column('companies', 'vertical')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('vertical', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_companies_vertical', 'companies', ['vertical'], unique=False)
    # ### end Alembic commands ###
