"""changed relationships in models

Revision ID: 76a41f56456f
Revises: e0b439eaa185
Create Date: 2024-11-20 08:40:48.729241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a41f56456f'
down_revision: Union[str, None] = 'e0b439eaa185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('call_summaries', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('call_summaries_contact_id_fkey', 'call_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'call_summaries', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.alter_column('companies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_companies_name', table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_index('ix_contacts_phone', table_name='contacts')
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.drop_constraint('contacts_company_id_fkey', 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key('contacts_company_id_fkey', 'contacts', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.create_index('ix_contacts_phone', 'contacts', ['phone'], unique=False)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index('ix_companies_name', 'companies', ['name'], unique=False)
    op.alter_column('companies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'call_summaries', type_='foreignkey')
    op.create_foreign_key('call_summaries_contact_id_fkey', 'call_summaries', 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')
    op.alter_column('call_summaries', 'summary',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
